- ThanhNien:
    id_type: href
    browser_profile: ''
    web_url: https://thanhnien.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //*[@id="abody"]/table[1]/tbody/tr[1]/td/img/@src
    - //*[@id="abody"]/table[1]/tbody/tr[1]/td/img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class="sapo"]/p
    - //div[@class="sapo"]/p
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://thanhnien.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //meta[@itemprop="datePublished"]/@content
    - //meta[@itemprop="datePublished"]/@content
    topic_type: href
    maximum_url: 50
    get_detail_content: true
    content_xpath:
    - //div[@id="abody"]
    - //div[@id="abody"]
    text_xpath:
    - .//p
    image_box_xpath:
    - .//table[@class="picture"]
    image_title_xpath:
    - .//td[@class="caption"]
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: xpath
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://thanhnien.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: false
    browser_timeout: 60
    prevent_auto_redirect: false
